# Generated by Django 4.0.2 on 2022-05-22 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('finance_lens_app', '0001_initial0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dobirth', models.DateField()),
                ('cust_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=5)),
                ('res_address', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('mar_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divoice')], default='Single', max_length=10)),
                ('mode_of_id', models.CharField(choices=[('Voters card', 'Voters card'), ('National identification', 'National identification'), ('Drivers License', 'Drivers License')], max_length=50)),
                ('id_no', models.CharField(max_length=100)),
                ('ref_no', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('mother_mai_name', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Others', 'Others')], default='Christian', max_length=10)),
                ('tin_no', models.CharField(max_length=50)),
                ('state_of_oringin', models.CharField(max_length=20)),
                ('local_govt_origin', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('off_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=10)),
                ('local_govt_res', models.CharField(max_length=20)),
                ('state_of_res', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('email_add', models.EmailField(max_length=30)),
                ('ocuppation', models.CharField(max_length=20)),
                ('acc_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_lens_app.coa')),
                ('br_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
