# Generated by Django 4.0.2 on 2022-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='res_address',
            field=models.TextField(max_length=200),
        ),
    ]
