# Generated by Django 4.0.2 on 2022-05-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_res_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='off_address',
            field=models.TextField(max_length=200),
        ),
    ]
