# Generated by Django 4.0.2 on 2022-05-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_sign_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sign',
            field=models.ImageField(upload_to='signs/'),
        ),
    ]
