# Generated by Django 4.0.2 on 2022-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_photo_alter_customer_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_sex',
            field=models.CharField(default='Male', max_length=5),
        ),
    ]
