# Generated by Django 4.0.2 on 2022-06-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_lens_app', '0001_initial0000'),
        ('customers', '0011_alter_customer_cust_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='acc_cat',
            field=models.ForeignKey(db_column='gl_no', on_delete=django.db.models.deletion.CASCADE, to='finance_lens_app.coa'),
        ),
    ]
