# Generated by Django 4.0.2 on 2022-06-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_lens_app', '0001_initial0000'),
        ('customers', '0014_alter_customer_acc_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='acc_cat',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='finance_lens_app.coa'),
        ),
    ]
