# Generated by Django 4.0.2 on 2022-05-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('br_code', models.CharField(choices=[('1', 'YBA')], max_length=50)),
                ('br_name', models.CharField(max_length=150)),
                ('br_address', models.CharField(max_length=100)),
                ('reg_no', models.IntegerField()),
                ('br_ses_date', models.DateField()),
                ('reg_date', models.DateField()),
                ('admin_name', models.CharField(max_length=50)),
            ],
        ),
    ]
