# Generated by Django 4.0.2 on 2022-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acct_head',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Aid', models.IntegerField()),
                ('head_name', models.CharField(max_length=200, unique=True)),
                ('gl_no', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'acct_head',
            },
        ),
        migrations.CreateModel(
            name='Acct_type',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('acct_type_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Acct_Type',
            },
        ),
        migrations.CreateModel(
            name='coa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gl_no', models.IntegerField(unique=True)),
                ('ac_name', models.CharField(max_length=200, unique=True)),
                ('ac_type', models.IntegerField()),
                ('ac_head', models.CharField(max_length=200)),
                ('currcy', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'coa',
            },
        ),
    ]
